CC = gcc
CFLAGS = -g -Wall -Wextra
CSTANDARD = -std=c11
RM = rm -f

default: all
all: question1 question2

question1: question1.c
	$(CC) $(CFLAGS) $(CSTANDARD) -o question1 question1.c

question2: question2.c
	$(CC) $(CFLAGS) $(CSTANDARD) -o question2 question2.c
